views/add.py
# -*- coding: utf-8 -*-
"""
Created on Wed Feb 28 15:48:28 2024

@author: jetth
"""

from flask import Blueprint, render_template, abort, request
from jinja2 import TemplateNotFound;
import database;

add = Blueprint("add", __name__, url_prefix="/add");

@add.route("/", methods=["GET", "POST"])
def index():
    try:
        return render_template(
            "add/index.html",
            title="Add",
            );
    except TemplateNotFound:
        abort(404);
    #end try
#end index()

@add.route("/result/", methods=["POST"])
def result():
    try:
        responseHeader = "";
        responseBody = "";
        
        try:
            name = request.form.get("name");
            iden = request.form.get("id");
            points = request.form.get("points");
        except:
            abort(400);
        #end try

        db = database.GetDatabase();
        cursor = db.cursor();

        cursor.execute("SELECT * FROM data WHERE id=@0", (iden,));
        if(cursor.fetchone() != None):
            responseHeader = "Failure";
            responseBody = "Entry with that ID exists already."
        else:
            cursor.execute("INSERT INTO data VALUES (?, ?, ?)", (name, iden, points));
            db.commit();
            
            responseHeader = "Success";
            responseBody = "The entry was added to the database."    
        #end if
        
        cursor.close();
        
        return render_template(
            "add/result.html",
            title="Add Result",
            responseHeader=responseHeader,
            responseBody=responseBody,
            );
    except TemplateNotFound:
        abort(404);
    #end try
#end index()

views/home.py
# -*- coding: utf-8 -*-
"""
Created on Tue Feb 20 16:02:54 2024

@author: jetth
"""

import database
from flask import Blueprint, render_template, abort, request
from jinja2 import TemplateNotFound;

home = Blueprint("home", __name__, url_prefix="/");

@home.route("/", methods=["GET", "POST"])
def index():
    try:
        db = database.GetDatabase();
        cursor = db.cursor();
        cursor.execute("SELECT * FROM data");
        tableData = cursor.fetchall();
        
        if(request.method == "POST"):
            searchReq = request.form.get("searchBtn", None);
            deleteReq = request.form.get("deleteBtn", None);
            
            if(searchReq != None):
                try:
                    searchName = request.form.get("name");
                    searchIden = request.form.get("id");
                    searchPoints = request.form.get("points");
                    
                    if(searchName != ""):
                        if(searchIden != ""):
                            if(searchPoints != ""):
                                cursor.execute("SELECT * FROM data WHERE name=@0 AND id=@1 AND points=@2", (searchName, searchIden, searchPoints,));
                                tableData = cursor.fetchall();
                            else:
                                cursor.execute("SELECT * FROM data WHERE name=@0 AND id=@1", (searchName, searchIden,));
                                tableData = cursor.fetchall();
                            #end if
                        elif(searchPoints != ""):
                            cursor.execute("SELECT * FROM data WHERE name=@0 AND points=@1", (searchName, searchPoints,));
                            tableData = cursor.fetchall();
                        else:
                            cursor.execute("SELECT * FROM data WHERE name=@0", (searchName,));
                            tableData = cursor.fetchall();
                        #end if
                    elif(searchIden != ""):
                        if(searchPoints != ""):
                            cursor.execute("SELECT * FROM data WHERE id=@0 AND points=@1", (searchIden, searchPoints,));
                            tableData = cursor.fetchall();
                        else:
                            cursor.execute("SELECT * FROM data WHERE id=@0", (searchIden,));
                            tableData = cursor.fetchall();
                        #end if
                    elif(searchPoints != ""):
                        cursor.execute("SELECT * FROM data WHERE points=@0", (searchPoints,));
                        tableData = cursor.fetchall();
                    #end if
                except:
                    abort(400);
                #end try
            elif(deleteReq != None):
                try:
                    deleteName = request.form.get("name");
                    deleteIden = request.form.get("id");
                    deletePoints = request.form.get("points");
                    
                    cursor.execute("DELETE FROM data WHERE name=@0 AND id=@1 AND points=@2", (deleteName, deleteIden, deletePoints,));
                    db.commit();
                    
                    cursor.execute("SELECT * FROM data");
                    tableData = cursor.fetchall();
                except:
                    abort(400);
                #end try
            #end if
        #end if
        
        return render_template(
            "home/index.html",
            title="Home",
            tableData=tableData,
            );
    except TemplateNotFound:
        abort(404);
    #end try
#end index()

views/update.py
# -*- coding: utf-8 -*-
"""
Created on Wed Feb 28 12:57:26 2024

@author: jetth
"""

from flask import Blueprint, render_template, abort, request
from jinja2 import TemplateNotFound;
import database;

update = Blueprint("update", __name__, url_prefix="/update");

@update.route("/", methods=["POST"])
def index():
    try:
        try:
            name = request.form.get("name");
            iden = request.form.get("id");
            points = request.form.get("points");
        except:
            abort(400);
        #end try
        
        return render_template(
            "update/index.html",
            title="Update",
            name=name,
            id=iden,
            points=points,
            );
    except TemplateNotFound:
        abort(404);
    #end try
#end index()

@update.route("/result/", methods=["POST"])
def result():
    try:
        responseHeader = "";
        responseBody = "";
        
        try:
            oldName = request.form.get("oldName");
            oldIden = request.form.get("oldId");
            oldPoints = request.form.get("oldPoints");
            
            name = request.form.get("name");
            iden = request.form.get("id");
            points = request.form.get("points");
        except:
            abort(400);
        #end try
        
        db = database.GetDatabase();
        cursor = db.cursor();
        
        if(oldIden != iden):
            cursor.execute("SELECT * FROM data WHERE id=@0", (iden,));
            if(cursor.fetchone() != None):
                responseHeader = "Failure";
                responseBody = "Entry with that ID exists already."
            else:
                cursor.execute("UPDATE data SET name=@0, id=@1, points=@2 WHERE name=@3 AND id=@4 AND points=@5", (name, iden, points, oldName, oldIden, oldPoints));
                db.commit();
                
                responseHeader = "Success";
                responseBody = "The entry was successfully updated."    
            #end if
        else:
            cursor.execute("UPDATE data SET name=@0, id=@1, points=@2 WHERE name=@3 AND id=@4 AND points=@5", (name, iden, points, oldName, oldIden, oldPoints));
            db.commit();
            
            responseHeader = "Success";
            responseBody = "The entry was successfully updated." 
        #end if
        
        cursor.close();
        
        return render_template(
            "update/result.html",
            title="Update Result",
            responseHeader=responseHeader,
            responseBody=responseBody
            );
    except TemplateNotFound:
        abort(404);
    #end try
#end index()

templates/SearchBar.html
<div class="row row-cols-5">
  <div class="container-fluid col-md-1 col-0" align="center"></div>
  <div class="container-fluid col-md-10 col-10 p-2 border-bottom border-black border-3" style="background: white; border-bottom-style: dashed !important;" align="center">
    <form action="{{ url_for('home.index') }}" method="POST">
      <div class="row row-cols-5" style="vertical-align: center;">
        <div class="col align-self-center">
          <h3 style="vertical-align: middle; margin:0px;">Search</h3>
        </div>
        <div class="col">
          <div style="display:inline"><label style="display: inline;">Name:</label><input class="form-control" style="display: inline;" type="text" name="name"></div>
        </div>
        <div class="col">
          <div style="display:inline"><label style="display: inline;">ID:</label><input class="form-control" style="display: inline;" type="number" name="id"></div>
        </div>
        <div class="col">
          <div style="display:inline"><label style="display: inline;">Points:</label><input class="form-control" style="display: inline;" type="number" name="points"></div>
        </div>
        <div class="col align-self-center">
          <button class="btn btn-info" name="searchBtn" type="submit" value="search">Search</button>
        </div>
      </div>
    </form>
  </div>
  <div class="container-fluid col-md-1 col-0" align="center"></div>
</div>

templates/add/index.html
{% extends "base.html" %}

{% block body %}
  <div class="container-fluid mt-3">
    <div class="col">
      <div class="row row-cols-5">
        <div class="container-fluid col-md-1 col-0" align="center"></div>
        <div class="container-fluid col-5 p-2 gap-2" style="background: white;" align="center">
          <form action="{{ url_for('add.result') }}" method="POST">
            <div class="col align-self-center p-2 m-2">
              <h3 style="vertical-align: middle; margin:0px;">Add Entry</h3>
              <div style="display:inline"><label style="display: inline;">Name:</label><input required class="form-control" style="display: inline;" type="text" name="name"></div>
              <div style="display:inline"><label style="display: inline;">ID:</label><input required class="form-control" style="display: inline;" type="number" name="id"></div>
              <div style="display:inline"><label style="display: inline;">Points:</label><input required class="form-control" style="display: inline;" type="number" name="points"></div>
            </div>
            <div class="col align-self-center">
              <button class="btn btn-info" name="searchBtn" type="submit" value="add">Add Entry</button>
            </div>
          </form>
        </div>
        <div class="container-fluid col-md-1 col-0" align="center"></div>
      </div>
    </div>
  </div>
{% endblock %}

templates/add/result.html
{% extends "base.html" %}

{% block body %}
  <div class="container-fluid mt-3">
    <div class="col">
      <div class="row row-cols-5">
        <div class="container-fluid col-md-2 col-0"></div>
        <div class="container-fluid col-md-3 col-5 p-2" style="background: white; overflow: auto;" align="center"  >
          <h3>{{ responseHeader}}</h3>
          <p>{{ responseBody }}</p>
          <div class="container-fluid row gap-2">
            <a class="container-fluid col p-0" href="{{ url_for('add.index') }}">
              <button class="container-fluid">Return</button>
            </a>
            <a class="container-fluid col p-0" href="{{ url_for('home.index') }}">
              <button class="container-fluid">Home</button>
            </a>
          </div>
        </div>
        <div class="container-fluid col-md-2 col-0" align="center"></div>
      </div>
    </div>
  </div>
{% endblock %}

templates/base.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% if title %}{{ title }}{% else %}Jet's Website{% endif %}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <link rel="stylesheet" href="/static/css/jetStyle.css">
  </head>
  <body class="dark-bg">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>

    <!--Global Navbar-->
    <nav class="navbar navbar-expand-lg dark-nav-bg">
      <div class="container-fluid">
        <a class="navbar-brand dark-text" href="{{ url_for('home.index') }}">Home</a>
        <button class="navbar-toggler dark-nav-toggle" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapsable" aria-controls="navbarCollapsable" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarCollapsable">
          <a class="nav-item btn btn-info" href="{{ url_for('add.index') }}">Add</a>
        </div>
      </div>
    </nav>
    <!--End Navbar-->

    <body class="dark-bg">
      {% block body %}{% endblock %}
    </body>
  </body>
</html>

templates/home/index.html
{% extends "base.html" %}

{% block body %}
  <div class="container-fluid mt-3">
    <div class="col">
      {% include "SearchBar.html" %}

      <div class="row row-cols-5">
        <div class="container-fluid col-md-1 col-0"></div>
        <div class="container-fluid col-md-10 col-10 p-2" style="background: white; overflow: auto;" align="center"  >
          <table class="table table-bordered table-striped table-light" style="vertical-align: middle;">
            <thead>
              <tr>
                <th>Name</th>
                <th>ID</th>
                <th>Points</th>
                <th>Update</th>
                <th>Delete</th>
              </tr>
            </thead>
            <tbody>
              {% for row in tableData %}
                <tr>
                  <td>{{ row[0] }}</td>
                  <td>{{ row[1] }}</td>
                  <td>{{ row[2] }}</td>
                  <form action="{{ url_for('update.index') }}" method="POST">
                    <input type="hidden" name="name" value="{{ row[0] }}">
                    <input type="hidden" name="id" value="{{ row[1] }}">
                    <input type="hidden" name="points" value="{{ row[2] }}">
                    <td><button class="btn btn-warning" name="updateBtn" type="submit" value="update">Update</button></td>
                  </form>
                  <form action="{{ url_for('home.index') }}" method="POST">
                    <input type="hidden" name="name" value="{{ row[0] }}">
                    <input type="hidden" name="id" value="{{ row[1] }}">
                    <input type="hidden" name="points" value="{{ row[2] }}">
                    <td><button class="btn btn-danger" name="deleteBtn" type="submit" value="delete">Delete</button></td>
                  </form>
                </tr>
              {% endfor %}
            </tbody>
          </table>
        </div>
        <div class="container-fluid col-md-1 col-0" align="center"></div>
      </div>
    </div>
  </div>
{% endblock %}

templates/update/index.html
{% extends "base.html" %}

{% block body %}
  <div class="container-fluid mt-3">
    <div class="col">
      <div class="row row-cols-5">
        <div class="container-fluid col-md-1 col-0" align="center"></div>
        <div class="container-fluid col-5 p-2 gap-2" style="background: white;" align="center">
          <form action="{{ url_for('update.result') }}" method="POST">
            <div class="col align-self-center p-2 m-2">
              <input type="hidden" name="oldName" value="{{ name }}">
              <input type="hidden" name="oldId" value="{{ id }}">
              <input type="hidden" name="oldPoints" value="{{ points }}">
              <h3 style="vertical-align: middle; margin:0px;">Update Entry</h3>
              <div style="display:inline"><label style="display: inline;">Name:</label><input required class="form-control" style="display: inline;" type="text" name="name" value="{{ name }}"></div>
              <div style="display:inline"><label style="display: inline;">ID:</label><input required class="form-control" style="display: inline;" type="number" name="id" value="{{ id }}"></div>
              <div style="display:inline"><label style="display: inline;">Points:</label><input required class="form-control" style="display: inline;" type="number" name="points" value="{{ points }}"></div>
            </div>
            <div class="col align-self-center">
              <button class="btn btn-info" name="searchBtn" type="submit" value="update">Update Entry</button>
            </div>
          </form>
        </div>
        <div class="container-fluid col-md-1 col-0" align="center"></div>
      </div>
    </div>
  </div>
{% endblock %}

templates/update/result.html
{% extends "base.html" %}

{% block body %}
  <div class="container-fluid mt-3">
    <div class="col">
      <div class="row row-cols-1" style="vertical-align: center;">
        <h3>Result</h3>
      </div>
      <div class="row row-cols-2" style="vertical-align: center;">
        <a class="btn" href="{{ url_for('update.index') }}">Return</a>
        <a class="btn" href="{{ url_for('home.index') }}">Home</a>
      </div>
      </div>
    </div>
  </div>
{% endblock %}